os: linux
arch:
 - amd64
 - ppc64le
language: c
compiler:
    - clang
    - gcc
before_script: autoreconf -i
script: ./configure && make && make check
after_failure: grep "^\[error\]" test/test-suite.log | head -n 50
